#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd,
# using the while loop + IFS.

while IFS=':' read -r username password uid gid name homedir shell; do
  echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: USER ID INFO"
done < /etc/passwd
