#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)

for file in *; do
  if [ "${file:0:1}" != "." ] && [ -f "$file" ]; then
    filename=$(echo "$file" | cut -d'-' -f2-)
    echo "$filename"
  fi
done
